"""
Tracking Visualizer
====================
Draws player bounding boxes and IDs on the video using the
per_frame_tracks.json already generated by run_demo.py.

Usage:
    python scripts/visualize_tracking.py \
        --video "input_videos/test (2).mp4" \
        --tracks "demo/demo_outputs/test (2)/per_frame_tracks.json" \
        --output "demo/demo_outputs/test (2)/tracked_output.mp4"
"""

import cv2
import json
import argparse
import sys
from pathlib import Path

# Team colours (BGR format for OpenCV)
TEAM_COLORS = {
    "A":  (60,  60,  220),   # Red  (home)
    "B":  (220, 130,  30),   # Blue (away)
    "?":  (160, 160, 160),   # Grey (unknown)
}
BALL_COLOR   = (0, 255, 255)   # Yellow
TEXT_COLOR   = (255, 255, 255) # White
BOX_THICKNESS = 2
FONT          = cv2.FONT_HERSHEY_SIMPLEX


def draw_frame(frame, detections: list, frame_w: int, frame_h: int,
               proc_w: int = 640, proc_h: int = 360):
    """Draw all boxes + labels for one frame.
    bbox format: [cx, cy, w, h] in processing resolution (640x360).
    We scale up to the original video resolution.
    """
    scale_x = frame_w / proc_w
    scale_y = frame_h / proc_h

    for det in detections:
        # bbox = [cx, cy, w, h] in processing coords
        bbox = det.get("bbox", [])
        if len(bbox) == 4:
            cx, cy, bw, bh = bbox
            x1 = int((cx - bw / 2) * scale_x)
            y1 = int((cy - bh / 2) * scale_y)
            x2 = int((cx + bw / 2) * scale_x)
            y2 = int((cy + bh / 2) * scale_y)
        else:
            continue   # skip if no bbox

        cls   = det.get("class", "person")
        tid   = det.get("track_id", "?")
        team  = det.get("team", "?")
        conf  = det.get("conf", 0.0)

        if cls == "ball":
            color = BALL_COLOR
            label = "Ball"
        else:
            color = TEAM_COLORS.get(str(team), TEAM_COLORS["?"])
            label = f"P{tid} ({team})"

        # Draw box
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, BOX_THICKNESS)

        # Draw label background
        (tw, th), _ = cv2.getTextSize(label, FONT, 0.45, 1)
        cv2.rectangle(frame, (x1, y1 - th - 6), (x1 + tw + 4, y1), color, -1)

        # Draw label text
        cv2.putText(frame, label, (x1 + 2, y1 - 4),
                    FONT, 0.45, TEXT_COLOR, 1, cv2.LINE_AA)

    return frame


def main():
    parser = argparse.ArgumentParser(description="TactiVision Tracking Visualizer")
    parser.add_argument("--video",  required=True, help="Path to original video")
    parser.add_argument("--tracks", required=True, help="Path to per_frame_tracks.json")
    parser.add_argument("--output", required=True, help="Output video path (.mp4)")
    parser.add_argument("--max-frames", type=int, default=0,
                        help="Limit frames (0 = all frames)")
    args = parser.parse_args()

    video_path  = Path(args.video)
    tracks_path = Path(args.tracks)
    output_path = Path(args.output)

    if not video_path.exists():
        print(f"ERROR: Video not found: {video_path}")
        sys.exit(1)
    if not tracks_path.exists():
        print(f"ERROR: Tracks file not found: {tracks_path}")
        sys.exit(1)

    # --- Load tracking data ---
    print(f"Loading tracking data from {tracks_path.name} ...")
    with open(tracks_path, encoding="utf-8") as f:
        raw = json.load(f)

    # Build frame_index → list of detections
    frames_data: dict[int, list] = {}
    if isinstance(raw, list):
        # Format: [{frame_idx, tracks:[...]}, ...]
        for entry in raw:
            fidx = entry.get("frame_idx", entry.get("frame", 0))
            frames_data[fidx] = entry.get("tracks", entry.get("detections", []))
    elif isinstance(raw, dict):
        # Format: {video:.., fps:.., frames:[{frame_idx, tracks:[...]}, ...]}
        if "frames" in raw and isinstance(raw["frames"], list):
            for entry in raw["frames"]:
                fidx = entry.get("frame_idx", 0)
                frames_data[fidx] = entry.get("tracks", [])
        else:
            for k, v in raw.items():
                try:
                    frames_data[int(k)] = v if isinstance(v, list) else []
                except ValueError:
                    pass

    print(f"  Loaded {len(frames_data)} frames of tracking data")

    # --- Open video ---
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"ERROR: Cannot open video: {video_path}")
        sys.exit(1)

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps          = cap.get(cv2.CAP_PROP_FPS) or 25.0
    frame_w      = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_h      = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    limit = args.max_frames if args.max_frames > 0 else total_frames
    print(f"  Video: {frame_w}x{frame_h} @ {fps:.1f} FPS | {total_frames} total frames")
    print(f"  Will render: {min(limit, total_frames)} frames")

    # --- Output video writer ---
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out    = cv2.VideoWriter(str(output_path), fourcc, fps, (frame_w, frame_h))

    # --- Process frames ---
    frame_idx = 0
    rendered  = 0
    print("Rendering tracked video ...")

    while cap.isOpened() and frame_idx < limit:
        ret, frame = cap.read()
        if not ret:
            break

        detections = frames_data.get(frame_idx, [])
        frame = draw_frame(frame, detections, frame_w, frame_h)

        # HUD — top left info bar
        hud = f"Frame {frame_idx} | Players: {len([d for d in detections if d.get('class') != 'ball'])}"
        cv2.putText(frame, hud, (10, 25), FONT, 0.6, (200, 200, 200), 1, cv2.LINE_AA)

        # Team legend
        cv2.putText(frame, "Team A (Home)", (10, frame_h - 40), FONT, 0.5, TEAM_COLORS["A"], 1)
        cv2.putText(frame, "Team B (Away)", (10, frame_h - 20), FONT, 0.5, TEAM_COLORS["B"], 1)

        out.write(frame)
        frame_idx += 1
        rendered  += 1

        if rendered % 50 == 0:
            pct = 100 * rendered / min(limit, total_frames)
            print(f"  {rendered}/{min(limit, total_frames)} frames ({pct:.0f}%)")

    cap.release()
    out.release()

    size_mb = output_path.stat().st_size / 1024 / 1024
    print(f"\nDone! Saved to: {output_path}  ({size_mb:.1f} MB)")
    print(f"Rendered {rendered} frames.")


if __name__ == "__main__":
    main()
